help/urls.py
from django.urls import path
from . import views


app_name = 'help'

urlpatterns = [
    path('make-a-ticket/', views.MakeTicket.as_view(), name='makeTicket'),
]

resume/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Путь к главной странице резюме
    path('resumes/', views.ResumesHome.as_view(), name='resumes'),

    # Путь для удаления резюме по его первичному ключу (pk)
    path('resume/<int:pk>/delete/', views.delete_resume, name='delete_resume'),

    # Путь для отображения резюме по его первичному ключу (pk)
    path('resume/<int:pk>/', views.ShowResume.as_view(), name='showResume'),

    # Путь для сортировки резюме
    path('sort-resumes/', views.SortResumes.as_view(), name='sortResumes'),

    # Путь для фильтрации резюме
    path('filtering-resumes/', views.FilteringResumes.as_view(), name='filteringResumes'),

    # Путь для поиска резюме
    path('search-resumes/', views.SearchResumes.as_view(), name='searchResumes'),

    # Путь для создания нового резюме
    path('create-resume/', views.createResume, name='createResume'),

    # Путь для обновления резюме по ID резюме
    path('update-resume/<int:resume_id>', views.updateResume, name='updateResume'),

    # Путь для удаления фотографии резюме по ID фотографии
    path('resume/<int:photo_id>/delete-photo/', views.delete_resume_photo, name='delete_resume_photo'),
]

staffsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # URL для административного интерфейса
    path('', RedirectView.as_view(url='resumes', permanent=True), name='index'),  # Редирект на 'resumes'
    path('', include('resume.urls')),  # Включение URL-ов приложения 'resume'
    path('', include('services.urls')),  # Включение URL-ов приложения 'services'
    path('', include('vacancy.urls')),  # Включение URL-ов приложения 'vacancy'
    path('users/', include('users.urls', namespace='users')),  # Включение URL-ов приложения 'users' с пространством имен
    path('info/', include('info.urls', namespace='info')),  # Включение URL-ов приложения 'info' с пространством имен
    path('help/', include('help.urls', namespace='help')),  # Включение URL-ов приложения 'help' с пространством имен
    path('__debug__/', include("debug_toolbar.urls")),  # URL для панели отладки
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Настройка URL для медиафайлов

resume/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from djmoney.models.fields import MoneyField
from datetime import date


# Create your models here.


class Resume(models.Model):
    EMPLOYMENT_CHOICES = (  # Выбор типов занятости
        ('full-time', 'Полная'),
        ('part-time', 'Частичная'),
        ('shift work', 'Вахтовая'),
        ('freelance', 'Фриланс'),
        ('temporary', 'Временная работа'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='resumes')
    name = models.CharField(max_length=50, verbose_name='Имя', blank=False)
    lastname = models.CharField(max_length=100, verbose_name='Фамилия', blank=False)
    date_birth = models.DateField(max_length=8, verbose_name='Дата рождения', blank=False)
    city = models.CharField(max_length=50, verbose_name='Город', blank=False)
    removal = models.BooleanField(default=False, verbose_name='Готовность к переезду', blank=True)
    remote_work = models.BooleanField(default=False, verbose_name='Удалённая работа', blank=True)
    phone = models.CharField(max_length=12, verbose_name='Телефон', blank=False)
    email = models.EmailField(max_length=100, verbose_name='Электронная почта', blank=False)
    post = models.CharField(max_length=100, verbose_name='Должность', blank=False )
    salary = MoneyField(max_digits=10, decimal_places=2, default_currency='RUB', verbose_name='Зарплата', blank=False)
    employment = models.CharField(max_length=10, choices=EMPLOYMENT_CHOICES, blank=False, default='full-time',
                                  verbose_name='Тип занятости')
    photo = models.ImageField(upload_to='photo/%Y/%m/%d', default=None, blank=True, null=True)
    resume_file = models.FileField(upload_to='resume/%Y/%m/%d', default=None, blank=True, null=True)
    date_uploaded = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания резюме')
    date_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления резюме')

    def clean_salary(self):  # Проверка, что значение salary содержит только цифры
        salary = self.cleaned_data.get('salary')

        # Проверка, что значение salary содержит только цифры
        if salary is not None:
            if not str(salary).isdigit():
                raise ValidationError("Поле 'Зарплата' должно содержать только цифры.")

        return salary

    def get_age(self):  # Вычисление возраста на основе даты рождения
        return (date.today() - self.date_birth).days // 365

    def get_true_age(self):  # Форматирование возраста с учетом грамматических правил
        age = self.get_age()
        suffix = "лет"
        if (age // 10) % 10 != 1:
            if age % 10 == 1:
                suffix = "год"
            elif age % 10 in (2, 3, 4) and not (age in [12, 13, 14]):
                suffix = "года"
        return f"{age} {suffix}"

    def __str__(self):  # Формат вывода объектов резюме
        return f"Резюме {self.post} {self.salary}"

    class Meta:
        verbose_name = 'Резюме'  # Имя для единственного числа
        verbose_name_plural = 'Резюме'  # Имя для множественного числа


class WorkExperience(models.Model):
    EXPERIENCE_CHOICES = (
        ('without-experience', 'Без опыта'),
        ('less-than-year', 'Менее года'),
        ('1', '1 год'),
        ('2', '2 года'),
        ('3', '3 года'),
        ('4', '4 года'),
        ('5', '5 лет'),
        ('6', '6 лет'),
        ('7', '7 лет'),
        ('8', '8 лет'),
        ('9', '9 лет'),
        ('10', '10 лет'),
        ('more-than-10', 'Более 10 лет'),
    )
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, related_name='work_experience')
    position = models.CharField(max_length=100, verbose_name='Должность', blank=True, null=True)
    company_name = models.CharField(max_length=100, verbose_name='Название компании', blank=True, null=True)
    start_date = models.DateField(max_length=8, verbose_name='Дата начала работы', blank=True, null=True)
    end_date = models.DateField(max_length=8, verbose_name='Дата окончания работы', default=None, blank=True, null=True)
    right_now = models.BooleanField(default=0, verbose_name='По настоящее время', blank=True)
    experience = models.CharField(max_length=18, choices=EXPERIENCE_CHOICES, verbose_name='Стаж')
    description = models.TextField(verbose_name='Обязанности', default='', blank=True)
    achievements = models.TextField(verbose_name='Достижения', default='', blank=True)

    class Meta:
        verbose_name = 'Опыт работы'
        verbose_name_plural = 'Опыт работы'


class Education(models.Model):
    DEGREE_CHOICES = (
        ('doctor of science', 'Доктор наук'),
        ('candidate of sciences', 'Кандидат наук'),
        ('higher education', 'Высшее образование'),
        ('incomplete higher education', 'Неполное высшее образование'),
        ('secondary specialized education', 'Среднее специальное образование'),
        ('secondary education', 'Среднее образование'),
        ('bachelor', 'Бакалавр'),
        ('magister', 'Магистр'),
    )
    EDUCATION_CHOICES = (
        ('full-time', 'Очное'),
        ('evening', 'Вечернее'),
        ('full-part-time', 'Очно-заочное'),
        ('part-time', 'Заочное'),
        ('distance ', 'Дистанционное'),
    )
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, related_name='education')
    degree = models.CharField(max_length=31, choices=DEGREE_CHOICES, verbose_name='Уровень образования')
    form_of_education = models.CharField(max_length=14, choices=EDUCATION_CHOICES, verbose_name='Форма обучения')
    year_of_graduation = models.PositiveIntegerField(validators=[MinValueValidator(1984)], verbose_name='Год окончания')
    educational_institution = models.CharField(max_length=100, verbose_name='Название учебного заведения')
    faculty = models.CharField(max_length=100, default='', blank=True, verbose_name='Факультет')
    specialty = models.CharField(max_length=150, default='', blank=True, verbose_name='Специальность')

    class Meta:
        verbose_name = 'Образование'
        verbose_name_plural = 'Образование'

class Portfolio(models.Model):
    resume = models.OneToOneField('Resume', on_delete=models.CASCADE, related_name='portfolio')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')

    class Meta:
        verbose_name = 'Портфолио'
        verbose_name_plural = 'Портфолио'


class Photos(models.Model):
    portfolio = models.ForeignKey('Portfolio', on_delete=models.CASCADE, related_name='photos')
    image = models.ImageField(upload_to='photo/resume_images/%Y/%m/%d', verbose_name='Фото для портфолио',
                              blank=True, null=True)

    class Meta:
        verbose_name = 'Фотографию'
        verbose_name_plural = 'Фотографии'


class ProfessionalSkills(models.Model):
    resume = models.OneToOneField('Resume', on_delete=models.CASCADE, related_name='professional_skills')
    skills = models.TextField(verbose_name='Навыки', blank=True, null=True)

    class Meta:
        verbose_name = 'Навыки'
        verbose_name_plural = 'Навыки'


class About(models.Model):
    resume = models.OneToOneField('Resume', on_delete=models.CASCADE, related_name='about')
    biography = models.TextField(verbose_name='Дополнительные сведения', blank=True, null=True)

    class Meta:
        verbose_name = 'Дополнительные сведения'
        verbose_name_plural = 'Дополнительные сведения'

resume/templates/resume/createResume.html
{% extends 'logo_menu.html'%}
{% load static %}
{% block content %}
<!-- Блок Общие данные -->
<form class="center-container" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="padding: 55px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Общие данные</h2>
                    {{form_rf.non_field_errors }}
                    {% for field in form_rf %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Конец блока Общие данные -->

    <!-- Блок Опыт работы -->
    <div style="padding: 20px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Опыт работы</h2>
                    {{form_wef.non_field_errors}}
                    {% for field in form_wef %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Конец блока Опыт работы -->

    <!-- Блок Образование -->
    <div style="padding: 20px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Образование</h2>
                    {{form_ef.non_field_errors}}
                    {% for field in form_ef %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Конец блока Образование -->

    <!-- Блок Обо мне -->
    <div style="padding: 20px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Обо мне</h2>
                    {{form_af.non_field_errors}}
                    {% for field in form_af %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Конец блока Обо мне -->
    <!-- Блок Проф навыки -->
    <div style="padding: 20px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Профессиональные навыки</h2>
                    {{form_psf.non_field_errors}}
                    {% for field in form_psf %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Блок Портфолио -->
    <div style="padding: 20px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Портфолио</h2>
                    {{form_pf.non_field_errors}}
                    {% for field in form_pf %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    <!-- Портфолио -->
                    <div class="col-mb-12">
                        <label class="form-label">Ваши работы</label>
                        <div class="image-preview">
                            {% for photo in photos %}
                            <div class="existing-photo-item mb-2" style="display: inline-block; margin-right: 10px;">
                                <img src="{{ photo.image.url }}" alt="Фото"
                                     class="preview-image" >
                                <p>
                                    <a href="{% url 'delete_resume_photo' photo.pk %}"
                                       class="btn btn-danger btn-sm">Удалить</a>
                                </p>
                            </div>
                            {% empty %}
                            {% if request.resolver_match.view_name != 'createResume' %}
                            <p>Нет существующих работ в портфолио.</p>
                            {% endif %}
                            {% endfor %}
                        </div>
                        <input type="file" name="images" id="image-input" value="{{photos}}" class="form-control"
                               multiple>
                    </div>
                    <div id="image-preview" class="image-preview"></div>
                    {% include 'includes/btns_submit_reset.html'%}
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Конец блока Портфолио -->
<script src="{% static 'js/images.js' %}"></script>
<script src="{% static 'resume/js/end_date.js' %}"></script>
{% endblock %}

resume/templates/resume/listResumes.html
{% extends 'base.html' %}
{% load static %}

{% block filters %}
<!-- Блок Фильтры -->
        <div class="col-3">
            <div class="filters">
                <h2 class="mb-3 fs-3">Фильтры</h2>
                <form action="{% url 'filteringResumes' %}" name="customer-form">

                    <!-- Зарплата -->
                    <div class="mb-3">
                        <label class="form-label">Зарплата</label>
                        <div class="input-group mb-3">
                            <span class="input-group-text">от</span>
                            <input type="number" name="salary_min" value="{{salary_min}}" class="form-control"
                                   placeholder="0">
                            <span class="input-group-text">₽</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text">до</span>
                            <input type="number" name="salary_max" value="{{salary_max}}" class="form-control"
                                   placeholder="100000">
                            <span class="input-group-text">₽</span>
                        </div>
                    </div>

                    <!-- Возраст -->
                    <div class="mb-3">
                        <label class="form-label">Возраст</label>
                        <div class="mb-3">
                            <div class="input-group mb-3">
                                <span class="input-group-text">от</span>
                                <input type="text" name="age_min" value="{{age_min}}" class="form-control"
                                       placeholder="18">
                                <span class="input-group-text">до</span>
                                <input type="text" name="age_max" value="{{age_max}}" class="form-control"
                                       placeholder="65">
                                <span class="input-group-text">лет</span>
                            </div>
                        </div>
                    </div>

                    <!-- Опыт работы -->
                    <div class="mb-3">
                        <label class="form-label">Опыт работы</label>
                        <select
                                name="work_experience"
                                id="work_experience"
                                class="form-select"
                        >
                            <option value=""></option>
                            {% for exp in Experience %}
                            <option value="{{exp.0}}" {% if work_experience == exp.0 %}selected{% endif %}>{{exp.1}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <!-- Тип занятости -->
                    <div class="mb-3">
                        <label class="form-label">Тип занятости</label>
                        <select
                                name="employment_type"
                                id="employment_type"
                                class="form-select"
                        >
                            <option value=""></option>
                            {% for emp in Employment %}
                            <option value="{{emp.0}}" {% if employment_type == emp.0 %}selected{% endif %}>{{emp.1}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <!-- Образование -->
                    <div class="mb-3">
                        <label class="form-label">Образование</label>
                        <select
                                name="education_type"
                                id="education"
                                class="form-select"
                        >
                            <option value=""></option>
                            {% for educ in Education %}
                            <option value="{{educ.0}}" {% if education_type == educ.0 %}selected{% endif %}>{{educ.1}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="r10"></div>
                    <button type="submit" class="btn btn-custom">Применить</button>
                    <a href="{% url 'index' %}" type="btn" class="btn btn-danger">Сбросить</a>
                </form>
            </div>
        </div>
        <!-- Конец блока фильтры -->
        {% endblock %}

        {% block Sort %}
        <!-- Сортировка -->
        <div class="col-8">
            <form action="{% url 'sortResumes' %}" method="get">
                <div class="input-group">

                    <select
                            class="form-select"
                            id="inputGroupSelect04"
                            aria-label="Выберите сортировку..."
                            name="sort_field"
                    >
                        <option value="" {% if type_sort == '' %}selected{% endif %}>Сортировать по...</option>
                        <option value="sort_date" {% if type_sort == 'sort_date' %}selected{% endif %}>По дате</option>
                        <option value="sort_age" {% if type_sort == 'sort_age' %}selected{% endif %}>По возрасту</option>
                    </select>
                    <button class="btn btn-outline-secondary" type="submit">
                        Сортировать
                    </button>
                </div>
            </form>
            {% endblock%}

            {% block content %}
            {% for resume in resumes %}
            <div class="r15"></div>
          <div class="girl">
            <div class="container">
              <div class="row">
                <div class="col-4">
                  <div class="image-content__main">
                    <div class="card-image__main">
                        {% if resume.photo %}
                      <img src="{{ resume.photo.url }}" alt="" class="card-img__main">
                        {% else %}
                      <img src="{{ default_user_image }}" alt="" class="card-img__main">
                        {% endif %}
                    </div>
                  </div>
                </div>
                <div class="col-7">
                  <span class="text_upd">Обновлено {{resume.date_update }} </span><br>
                <a href="{% url 'showResume' resume.pk %}" class="text_name"><b>{{ resume.post }}</b></a><br>
                <span class="some_text"><b>{{ resume.salary }}</b></span>
                <div class="some_text">
                    <b>{{ resume.about.biography|truncatechars:350 }}</b>
                    {% if resume.professional_skills.skills != '' %} <br>{{ resume.professional_skills.skills|truncatechars:100}}{% endif %}

                    <p>Опыт работы {% for work in resume.work_experience.all %}{{ work.get_experience_display }} {% empty %} Нет данных об опыте работы {% endfor %}.

                        Образование {% for education in resume.education.all %} {{ education.get_degree_display }} {% empty %} Нет данных об образовании {% endfor %}.<br>
                        {{ resume.get_true_age }} {{ resume.city }}
                        {% if resume.removal %}
                        готов(а) к переезду
                        {% else %}
                        не готов(а) к переезду
                        {% endif %}
                    </p>
                </div>
                    <a href="{% url 'showResume' resume.pk %}" type="button" class="btn btn-custom">Получить контакты</a>
                </div>
                </div>
              </div>
            </div>
                {% empty %}
                <div class="r5"></div>
                <p class="text_name"> Резюме по заданным критериям не найдено</p>
                {% endfor %}
            </div>
            {% endblock %}

resume/templates/resume/resume.html
{% extends 'logo_menu.html'%}
{% load static %}
{% block content %}
<div style="padding: 40px"></div>
<div class="container">
    <div class="show-container">
        <h1>{{ resume.name }} {{ resume.lastname }}</h1>
        {% if resume.photo %}
        <img src="{{ resume.photo.url }}" alt="Фото" class="profile-photo">
        {% else %}
        <img src="{{ default_image }}" alt="Фото" class="profile-photo">
        {% endif %}
        <p><strong>Дата рождения:</strong> {{ resume.date_birth }}</p>
        <p><strong>Возраст:</strong> {{ resume.get_true_age }}</p>
        <p><strong>Город:</strong> {{ resume.city }}</p>
        <p><strong>Телефон:</strong> {{ resume.phone }}</p>
        <p><strong>Электронная почта:</strong> {{ resume.email }}</p>
        <p><strong>Должность:</strong> {{ resume.post }}</p>
        <p><strong>Зарплата:</strong> {{ resume.salary }}</p>
        <p><strong>Тип занятости:</strong> {{ resume.get_employment_display }}</p>
        <p><strong>Готовность к переезду:</strong> {{ resume.removal|yesno:"Да,Нет" }}</p>
        <p><strong>Удалённая работа:</strong> {{ resume.remote_work|yesno:"Да,Нет" }}</p>
    </div>

    <div class="show-container">
        <h2 class="section-title">Опыт работы</h2>
        {% for experience in resume.work_experience.all %}
            <div>
                {% if experience.position %}<h5>{{ experience.position }} в {{ experience.company_name }}</h5>{% endif %}
                {% if experience.start_date %}<p><strong>Период:</strong> {{ experience.start_date }} - {% if experience.right_now %} по настоящее время {% else %} {{ experience.end_date }} {% endif %}</p>{% endif %}
                <p><strong>Стаж:</strong> {{ experience.get_experience_display }}</p>

                {% if experience.description %}<p><strong>Обязанности:</strong> {{ experience.description }}</p> {% endif %}
                {% if experience.achievements %}<p><strong>Достижения:</strong> {{ experience.achievements }}</p> {% endif %}
                <hr>
            </div>
        {% empty %}
            <p>Нет информации об опыте работы.</p>
        {% endfor %}
    </div>

    <div class="show-container">
        <h2 class="section-title">Образование</h2>
        {% for education in resume.education.all %}
            <div>
                <h5>{{ education.educational_institution }} ({{ education.year_of_graduation }})</h5>
                <p><strong>Уровень образования:</strong> {{ education.get_degree_display }}</p>
                <p><strong>Форма обучения:</strong> {{ education.get_form_of_education_display }}</p>
                <p><strong>Специальность:</strong> {{ education.specialty }}</p>
                <hr>
            </div>
        {% empty %}
            <p>Нет информации об образовании.</p>
        {% endfor %}
    </div>

    <div class="show-container">
        <h2 class="section-title">Портфолио</h2>
        {% if resume.portfolio.description %}
            <p>{{ resume.portfolio.description }}</p>
            {% for photo in resume.portfolio.photos.all %}
                <div class="r5"></div>
                <a href="{{ photo.image.url }}"><img src="{{ photo.image.url }}" alt="Фото портфолио" class="img-thumbnail" ></a>
            {% endfor %}
        {% else %}
            <p>Портфолио отсутствует.</p>
        {% endif %}
    </div>
    {% if resume.professional_skills.skills %}
    <div class="show-container">
        <h2 class="section-title">Профессиональные навыки</h2>
        <p>{{ resume.professional_skills.skills }}</p>
    </div>
    {% endif %}
    {% if resume.about.biography %}
    <div class="show-container">
        <h2 class="section-title">Дополнительные сведения</h2>
        <p>{{ resume.about.biography }}</p>
    </div>
    {% endif %}
</div>

{% endblock %}