help/urls.py
from django.urls import path
from . import views


app_name = 'help'

urlpatterns = [
    path('make-a-ticket/', views.MakeTicket.as_view(), name='makeTicket'),
]

staffsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # URL для административного интерфейса
    path('', RedirectView.as_view(url='resumes', permanent=True), name='index'),  # Редирект на 'resumes'
    path('', include('resume.urls')),  # Включение URL-ов приложения 'resume'
    path('', include('services.urls')),  # Включение URL-ов приложения 'services'
    path('', include('vacancy.urls')),  # Включение URL-ов приложения 'vacancy'
    path('users/', include('users.urls', namespace='users')),  # Включение URL-ов приложения 'users' с пространством имен
    path('info/', include('info.urls', namespace='info')),  # Включение URL-ов приложения 'info' с пространством имен
    path('help/', include('help.urls', namespace='help')),  # Включение URL-ов приложения 'help' с пространством имен
    path('__debug__/', include("debug_toolbar.urls")),  # URL для панели отладки
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Настройка URL для медиафайлов

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register_company/', views.RegisterEmployer.as_view(), name='register_company'),
    path('register_done/', views.RegisterDone.as_view(), name='register_done'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

templates/base.html
{% load static %}


<html lang="ru">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{{ title }}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <link type="text/css" rel="stylesheet" href="{% static 'css/normalize.min.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% block head %}
    {% endblock %}
    <link
            type="text/css"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
    />
</head>
<body>
<!-- Шапка -->
<div class="header">
    {% include 'includes/btn_bars.html'%}
    <header class="header__c container">
        {% include 'includes/index_logo.html'%}


        <form action="{% url sort_url %}" class="form" method="get">
            <button class="form__button" type="submit"><img src="{% static 'img/search.svg' %}"></button>
            <input
                    class="form__input"
                    type="search"
                    placeholder="{{sort_placeholder}}"
                    name="q"
                    value="{{ search_query }}"
            />
        </form>

    </header>
    <nav class="header__nav">
        <ul class="header__list">
            <li class="header__item">
                <a href="{% url 'help:makeTicket' %}" class="header__link_header">
                    <img class="icon" src="{% static 'img/help.svg' %}">
                    Помощь
                </a>
            </li>
            <li class="header__item">
                {% if request.user.is_authenticated %}
            <li class="header__item">
                <a class="header__link_header" href="{% url 'users:profile' %}">
                    <img class="icon" src="{% static 'img/user.svg' %}">
                    Профиль
                </a>
            </li>
            <a class="header__link_header" href="{% url 'users:logout' %}">
                <img class="icon" src="{% static 'img/login.svg' %}">
                Выйти
            </a>
            {% else %}
            <a class="header__link_header" href="{% url 'users:login' %}">
                <img class="icon" src="{% static 'img/login.svg' %}">
                Вход
            </a>
            {% endif %}

        </ul>
    </nav>
</div>
<!-- Конец Шапки -->


<!-- Меню -->
{% include 'includes/bur_menu.html'%}
<div style="padding: 55px"></div>
<div class="container">
    <div class="row">
    {% include 'includes/btns_select_view.html'%}

{% block filters %}

{% endblock %}

{% block Sort %}

{% endblock %}

<!-- Блоки резюме -->
{% block content %}

{% endblock %}

    </div>
</div>
</body>
</html>

templates/base_users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <link type = "text/css" rel="stylesheet" href="{% static 'css/normalize.min.css' %}" />
    <link type = "text/css" rel="stylesheet" href="{% static 'users/css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body >
    <div style="background: url({% static 'users/img/img.jpg' %}) no-repeat; background-size: cover;">

        {% block content %}

        {% endblock %}
</div>
</body>
</html>

templates/confirm_delete.html
{% extends 'logo_menu.html'%}
{% load static %}
{% block content %}
<div style="padding: 55px"></div>
<div class="show-container">
    {% if obj.image %}
    <h2>Вы уверены, что хотите удалить данное изображение?</h2>
    <img src="{{ obj.image.url }}" alt="Фото" class="img-thumbnail">
    {% else %}
    <h2>Вы уверены, что хотите удалить "{{ obj }}"?</h2>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <button class="btn btn-success" type="submit">Подтвердить</button>
        <button type="reset" class="btn btn-danger" onclick="goBack()">Отмена</button>
    </form>
</div>
<script src="{% static 'js/go_back.js' %}"></script>
{% endblock %}

templates/logo_menu.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,
                   initial-scale=1.0">
    <title>{{ title }}</title>
    <link type="image/x-icon" rel="icon" href="{% static 'img/favicon.ico' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/normalize.min.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% block head %}
    {% endblock %}
    <link
            type="text/css"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
    />
</head>

<body>
<div class="header">
    <header class="header__c">
        <div class="cont">
            <!-- Кнопка для показа меню -->
            {% include 'includes/btn_bars.html'%}
        </div>
        {% include 'includes/index_logo.html'%}
    </header>
</div>
<!-- Меню -->
{% include 'includes/bur_menu.html'%}
{% block content %}

{% endblock %}
</body>

</html>