help/urls.py
from django.urls import path
from . import views


app_name = 'help'

urlpatterns = [
    path('make-a-ticket/', views.MakeTicket.as_view(), name='makeTicket'),
]

staffsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # URL для административного интерфейса
    path('', RedirectView.as_view(url='resumes', permanent=True), name='index'),  # Редирект на 'resumes'
    path('', include('resume.urls')),  # Включение URL-ов приложения 'resume'
    path('', include('services.urls')),  # Включение URL-ов приложения 'services'
    path('', include('vacancy.urls')),  # Включение URL-ов приложения 'vacancy'
    path('users/', include('users.urls', namespace='users')),  # Включение URL-ов приложения 'users' с пространством имен
    path('info/', include('info.urls', namespace='info')),  # Включение URL-ов приложения 'info' с пространством имен
    path('help/', include('help.urls', namespace='help')),  # Включение URL-ов приложения 'help' с пространством имен
    path('__debug__/', include("debug_toolbar.urls")),  # URL для панели отладки
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Настройка URL для медиафайлов

vacancy/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create-vacancy/', views.createVacancy, name='createVacancy'),
    path('vacancy/<int:pk>/delete/', views.delete_vacancy, name='delete_vacancy'),
    path('vacancies/', views.ListVacancies.as_view(), name='vacancies'),
    path('vacancy/<int:pk>/', views.ShowVacancy.as_view(), name='showVacancy'),
    path('sort-vacancies/', views.SortVacancies.as_view(), name='sortVacancies'),
    path('filtering-vacancies/', views.FilteringVacancies.as_view(), name='filteringVacancies'),
    path('search-vacancies/', views.SearchVacancies.as_view(), name='searchVacancies'),
    path('update-vacancy/<int:vacancy_id>', views.updateVacancy, name='updateVacancy'),
]

vacancy/models.py
from users.models import Employer
from django.db import models
from djmoney.models.fields import MoneyField


# Create your models here.
class Vacancy(models.Model):
    company = models.ForeignKey(Employer, on_delete=models.CASCADE, related_name='vacancies')
    title = models.CharField(max_length=100, blank=False, verbose_name='Название вакансии')
    profession = models.CharField(max_length=50, blank=False, verbose_name='Профессия')
    field_of_activity = models.CharField(max_length=50, blank=False, verbose_name='Сфера деятельности')
    description = models.TextField(blank=False, verbose_name='Описание вакансии')
    photo = models.ImageField(upload_to='photo/%Y/%m/%d', default=None, blank=True, null=True,
                              verbose_name='Логотип или фотография')
    date_uploaded = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания вакансии')
    date_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления вакансии')

    def __str__(self):
        return f"Вакансия {self.title}"

    class Meta:
        verbose_name = "Вакансию"
        verbose_name_plural = "Вакансии"


class Conditions(models.Model):
    EMPLOYMENT_CHOICES = (
        ('full-time', 'Полный день'),
        ('free-work-schedule', 'Свободный'),
        ('shift-work', 'Вахтовый'),
        ('shifts', 'Сменный'),
    )
    CONTRACT_CHOICES = (
        ('employment-contract', 'Трудовой договор'),
        ('GPH-contract-with-sole-proprietor', 'Договор ГПХ с ИП'),
        ('GPH-contract-with-self-employed', 'Договор ГПХ с самозанятым'),
        ('GPH-contract-with-individual', 'Договор ГПХ с физлицом'),
    )
    FREQUENCY_CHOICES = (
        ('every-day', 'Каждый день'),
        ('twice-month', 'Дважды в месяц'),
        ('once-week', 'Раз в неделю'),
        ('once-month', 'Раз в месяц'),
    )
    vacancy = models.OneToOneField('Vacancy', on_delete=models.CASCADE, related_name='conditions')
    employment = models.CharField(max_length=18, choices=EMPLOYMENT_CHOICES, blank=False, default='full-time',
                                  verbose_name='Тип занятости')
    contract = models.CharField(max_length=33, choices=CONTRACT_CHOICES, default='employment-contract',
                                verbose_name='Способ оформления')
    salary = MoneyField(max_digits=14, decimal_places=2, default_currency='RUB', verbose_name='Зарплата')
    underworking = models.BooleanField(default=False, blank=True, verbose_name='Подработка')
    remote_work = models.BooleanField(default=False, verbose_name='Удалённая работа', blank=True)
    frequency_payments = models.CharField(max_length=11, choices=FREQUENCY_CHOICES, default='once-week',
                                          verbose_name='Частота выплат')
    what_employees_get = models.TextField(blank=True, null=True, verbose_name='Что получают работники')

    class Meta:
        verbose_name = "Условие"
        verbose_name_plural = "Условия"

vacancy/forms.py
from django import forms

from .models import Vacancy, Conditions


class VacancyForm(forms.ModelForm):
    title = forms.CharField(label='Название вакансии', widget=forms.TextInput(attrs={'class': 'form-control',
                                                                                     'placeholder': 'Например, "Срочно требуется сварщик 5 разряда"'}))

    profession = forms.CharField(label='Профессия', widget=forms.TextInput(attrs={'class': 'form-control',
                                                                                  'placeholder': 'Например, «Таргетолог» или «Электрик»'}))
    description = forms.CharField(label='Описание услуги',
                                  widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5,
                                                               'placeholder': 'Введите подробное описание вакансии...'}))

    field_of_activity = forms.CharField(label='Сфера деятельности',
                                        widget=forms.TextInput(attrs={'class': 'form-control',
                                                                      'placeholder': 'Введите сферу деятельности...'}))
    photo = forms.ImageField(label='Логотип или фотография', required=False,
                             widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Vacancy
        fields = ('title', 'profession', 'field_of_activity', 'description', 'photo')


class ConditionsForm(forms.ModelForm):
    employment = forms.ChoiceField(label='Тип занятости', choices=Conditions.EMPLOYMENT_CHOICES,
                                   widget=forms.Select(attrs={'class': 'form-select'}))
    contract = forms.ChoiceField(label='Способ оформления', choices=Conditions.CONTRACT_CHOICES,
                                 widget=forms.Select(attrs={'class': 'form-select'}))
    salary = forms.DecimalField(label='Зарплата', widget=forms.NumberInput(attrs={'class': 'form-control'}))
    underworking = forms.BooleanField(label='Подработка', required=False,
                                      widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    remote_work = forms.BooleanField(label='Удалённая работа', required=False,
                                     widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    frequency_payments = forms.ChoiceField(label='Частота выплат', choices=Conditions.FREQUENCY_CHOICES,
                                           widget=forms.Select(attrs={'class': 'form-select'}))
    what_employees_get = forms.CharField(label='Что получают работники', required=False,
                                         widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5,
                                                                      'placeholder':
                                                                          'Например, Проживание, Питание, Обучение, Медицинская страховка и тд.'}))

    class Meta:
        model = Conditions
        fields = (
            'employment', 'contract', 'salary', 'underworking', 'remote_work', 'frequency_payments',
            'what_employees_get')

vacancy/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

from .forms import VacancyForm, ConditionsForm
from .models import Vacancy
from .utils import DataMixin, ToolsMixin


@login_required(login_url='users:login')
def createVacancy(request, *args, **kwargs):
    if request.method == 'POST':
        form_vf = VacancyForm(request.POST, prefix='vacancy')
        form_cf = ConditionsForm(request.POST, prefix='conditions')

        if form_vf.is_valid() and form_cf.is_valid():
            vacancy_info = form_vf.save(commit=False)
            vacancy_info.company = request.user.employer
            vacancy_info.save()

            conditions_info = form_cf.save(commit=False)
            conditions_info.vacancy = vacancy_info
            conditions_info.save()

            return redirect('vacancies')
    else:
        form_vf = VacancyForm(prefix='vacancy')
        form_cf = ConditionsForm(prefix='conditions')
    data = {
        'title': 'Размещение вакансии',
        'form_vf': form_vf,
        'form_cf': form_cf,
    }
    return render(request, 'vacancy/createVacancy.html', context=data)


class ListVacancies(DataMixin, ListView):
    model = Vacancy

    def get_queryset(self):
        # Добавляем аннотацию к queryset
        return Vacancy.objects.all().select_related('conditions')


@login_required(login_url='users:login')
def delete_vacancy(request, pk):
    vacancy = get_object_or_404(Vacancy, pk=pk, company=request.user.employer)
    if request.method == 'POST':
        vacancy.delete()
        messages.success(request, 'Вакансия успешно удалена.')
        return redirect('vacancies')
    data = {
        'title': 'Удаление вакансии',
        'obj': vacancy
    }
    return render(request, 'confirm_delete.html', data)


class ShowVacancy(LoginRequiredMixin, DetailView):
    model = Vacancy
    template_name = 'vacancy/vacancy.html'
    context_object_name = 'vacancy'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Вакансия - {self.object.title}"
        return context


@login_required(login_url='users:login')
def updateVacancy(request, vacancy_id):
    vacancy_info = get_object_or_404(Vacancy, id=vacancy_id, company=request.user.employer)

    if request.method == 'POST':
        # Создаем формы с очищенными данными
        form_vf = VacancyForm(request.POST, instance=vacancy_info, prefix='vacancy')
        form_cf = ConditionsForm(request.POST, instance=vacancy_info.conditions, prefix='conditions')

        # Проверяем валидность форм
        if all(form.is_valid() for form in [form_vf, form_cf]):
            form_vf.save()
            form_cf.save()
            return redirect('index')

    else:
        form_vf = VacancyForm(instance=vacancy_info, prefix='vacancy')
        form_cf = ConditionsForm(instance=vacancy_info.conditions, prefix='conditions', initial={'salary': vacancy_info.conditions.salary.amount})

    photo = vacancy_info.photo
    data = {
        'title': 'Редактирование вакансии',
        'form_vf': form_vf,
        'form_cf': form_cf,
        'photo': photo,
    }
    return render(request, 'vacancy/createVacancy.html', context=data)


class SortVacancies(DataMixin, ToolsMixin, ListView):

    def get_queryset(self):
        type_sort = self.request.GET.get('sort_field')
        if type_sort == 'sort_data':
            return Vacancy.objects.all().order_by('-date_update')
        elif type_sort == 'sort_salary':
            return Vacancy.objects.all().order_by('-conditions__salary')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        type_sort = self.request.GET.get('sort_field', '')
        context['type_sort'] = type_sort
        return context


class FilteringVacancies(DataMixin, ToolsMixin, ListView):

    def get_queryset(self):
        queryset = Vacancy.objects.all()
        salary_min = self.request.GET.get('salary_min', '')
        salary_max = self.request.GET.get('salary_max', '')
        employment = self.request.GET.get('employment', '')
        contract = self.request.GET.get('contract', '')
        frequency = self.request.GET.get('frequency', '')
        underworking = self.request.GET.get('underworking', '')
        remote_work = self.request.GET.get('remote_work', '')

        if salary_min != '':
            queryset = queryset.filter(conditions__salary__gte=salary_min)
        if salary_max != '':
            queryset = queryset.filter(conditions__salary__lte=salary_max)
        if employment != '':
            queryset = queryset.filter(conditions__employment=employment)
        if contract != '':
            queryset = queryset.filter(conditions__contract=contract)
        if frequency != '':
            queryset = queryset.filter(conditions__frequency_payments=frequency)
        if underworking != '':
            queryset = queryset.filter(conditions__underworking=underworking)
        if remote_work != '':
            queryset = queryset.filter(conditions__remote_work=remote_work)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['salary_min'] = self.request.GET.get('salary_min', '')
        context['salary_max'] = self.request.GET.get('salary_max', '')
        context['employment'] = self.request.GET.get('employment', '')
        context['contract'] = self.request.GET.get('contract', '')
        context['frequency'] = self.request.GET.get('frequency', '')
        context['underworking'] = self.request.GET.get('underworking', '')
        context['remote_work'] = self.request.GET.get('remote_work', '')
        return context


class SearchVacancies(DataMixin, ToolsMixin, ListView):

    def get_queryset(self):
        return Vacancy.objects.filter(Q(title__icontains=self.request.GET.get('q')) |
                                      Q(profession__icontains=self.request.GET.get('q'))
                                      | Q(field_of_activity__icontains=self.request.GET.get('q'))
                                      | Q(description__icontains=self.request.GET.get('q')))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = self.request.GET.get('q', '')
        context['search_query'] = search_query
        return context

vacancy/templates/vacancy/createVacancy.html
{% extends 'logo_menu.html'%}
{% load static %}
{% block content %}
<!-- Блок Новая вакансия -->
<form class="center-container" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="padding: 55px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Описание вакансии</h2>
                    {{form_vf.non_field_errors }}
                    {% for field in form_vf %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% if photo %}
                    <div class="image-preview">
                            <div class="existing-photo-item mb-2" style="display: inline-block; margin-right: 10px;">
                                <img src="{{ photo.image.url }}" alt="Фото"
                                     class="preview-image" >
                                <p>
                                    <a href="#"
                                       class="btn btn-danger btn-sm">Удалить</a>
                                </p>
                            </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- Конец блока Новая вакансия -->

    <!-- Блок Условия для кандидата -->
    <div style="padding: 20px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Условия для кандидата</h2>
                    {{form_cf.non_field_errors}}
                    {% for field in form_cf %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    {% include 'includes/btns_submit_reset.html'%}
                </div>
            </div>
        </div>
    </div>
    <!-- Конец блока Условия для кандидата -->

</form>
{% endblock %}

vacancy/templates/vacancy/listVacancies.html
{% extends 'base.html' %}
{% load static %}

{% block filters %}
<!-- Блок Фильтры -->
        <div class="col-3">
            <div class="filters">
                <h2 class="mb-3 fs-3">Фильтры</h2>
                <form action="{% url 'filteringVacancies' %}" name="customer-form">

                    <!-- Зарплата -->
                    <div class="mb-3">
                        <label class="form-label">Зарплата</label>
                        <div class="input-group mb-3">
                            <span class="input-group-text">от</span>
                            <input type="number" name="salary_min" value="{{salary_min}}" class="form-control" placeholder="0">
                            <span class="input-group-text">₽</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text">до</span>
                            <input type="number" name="salary_max" value="{{salary_max}}" class="form-control" placeholder="100000">
                            <span class="input-group-text">₽</span>
                        </div>
                    </div>

                    <!-- Тип занятости -->
                    <div class="mb-3">
                        <label class="form-label">Тип занятости</label>
                        <select
                                name="employment"
                                id="employment"
                                class="form-select"
                        >
                            <option value=""></option>
                            {% for empl in Employment %}
                            <option value="{{empl.0}}" {% if employment == empl.0 %}selected{% endif %}>{{empl.1}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <!-- Способ оформления -->
                    <div class="mb-3">
                        <label class="form-label">Способ оформления</label>
                        <select
                                name="contract"
                                id="contract"
                                class="form-select"
                        >
                            <option value=""></option>
                            {% for cont in Contract %}
                            <option value="{{cont.0}}" {% if contract == cont.0 %}selected{% endif %}>{{cont.1}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <!-- Частота выплат -->
                    <div class="mb-3">
                        <label class="form-label">Частота выплат</label>
                        <select
                                name="frequency"
                                id="frequency"
                                class="form-select"
                        >
                            <option value=""></option>
                            {% for freq in Frequency %}
                            <option value="{{freq.0}}" {% if frequency == freq.0 %}selected{% endif %}>{{freq.1}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="yes" id="flexCheckUnderworking" name="underworking" {% if underworking %} checked {% endif %}>
                        <label class="form-check-label" for="flexCheckUnderworking">
                            Подработка
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="yes" id="flexCheckRemote_work" name="remote_work" {% if remote_work %} checked {% endif %}>
                        <label class="form-check-label" for="flexCheckRemote_work">
                            Удалённая работа
                        </label>
                    </div>
                    <div class="r10"></div>
                    <button type="submit" class="btn btn-custom">Применить</button>
                    <a href="{% url 'vacancies' %}" type="btn" class="btn btn-danger">Сбросить</a>
                </form>
            </div>
        </div>
        <!-- Конец блока фильтры -->
        {% endblock %}

        {% block Sort %}
        <!-- Сортировка -->
        <div class="col-8">
            <form action="{% url 'sortVacancies' %}" method="get">
                <div class="input-group">
                    <select
                            class="form-select"
                            id="inputGroupSelect04"
                            aria-label="Выберите сортировку..."
                            name="sort_field"
                    >
                        <option value="" {% if type_sort == '' %}selected{% endif %}>Сортировать по...</option>
                        <option value="sort_data" {% if type_sort == 'sort_data' %}selected{% endif %}>По дате обновления</option>
                        <option value="sort_salary" {% if type_sort == 'sort_salary' %}selected{% endif %}>По заработной плате</option>
                    </select>
                    <button class="btn btn-outline-secondary" type="submit">
                        Сортировать
                    </button>
                </div>
            </form>
            {% endblock%}

            {% block content %}
            {% for vacancy in vacancies %}
            <div class="r15"></div>
            <div class="girl">
                <div class="container">
                    <div class="row">
                        <div class="col-4">
                            <div class="image-content__main">
                                <div class="card-image__main">
                                    {% if vacancy.photo %}
                                    <img src="{{ vacancy.photo.url }}" alt="" class="card-img__main">
                                    {% else %}
                                    <img src="{{ default_image }}" alt="" class="card-img__main">
                                    {% endif %}
                                 </div>
                            </div>
                        </div>
                <div class="col-7">
                <span class="text_upd">Обновлено {{vacancy.date_update }} </span><br>
                <a href="{% url 'showVacancy' vacancy.pk %}" class="text_name"><b>{{ vacancy.title }}</b></a><br>
                <span class="text_name"><b>От {{ vacancy.conditions.salary }} </b></span>
                <div class="some_text">
                    Тип занятости:{{ vacancy.conditions.get_employment_display }}. Выплаты: {{ vacancy.conditions.get_frequency_payments_display }}.
                </div>
                <div class="some_text">
                    <b>{{ vacancy.description|truncatechars:150 }}</b><br>
                    <div class="r5"></div>
                    <p>Дополнительно {{ vacancy.conditions.what_employees_get }}.</p>
                </div>

                <a href="{% url 'showVacancy' vacancy.pk %}" type="button" class="btn btn-custom" >Подробнее</a>
            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
            <div class="r5"></div>
            <p class="text_name"> Вакансий по заданным критериям не найдено</p>
            {% endfor %}
            </div>
            {% endblock %}

vacancy/templates/vacancy/vacancy.html
{% extends 'logo_menu.html'%}
{% load static %}
{% block content %}
<div style="padding: 40px"></div>
<div class="container">
    <div class="show-container">
        <h1>{{ vacancy.title }}</h1>
        <p><strong>Компания:</strong> {{ vacancy.company.company_name }}</p>
        <p>{{ vacancy.company.company_description }}</p>
        <p><strong>Профессия:</strong> {{ vacancy.profession }}</p>
        <p><strong>Сфера деятельности:</strong> {{ vacancy.field_of_activity }}</p>

        {% if vacancy.photo %}<img src="{{ vacancy.photo.url }}" alt="Логотип компании" class="vacancy-photo">{% endif %}

        <div style=" clear: both;"></div>

        <p><strong>Описание вакансии:</strong></p>
        <p>{{ vacancy.description }}</p>
        <p><strong>Дата создания:</strong> {{ vacancy.date_uploaded }}</p>
    </div>

    <div class="show-container">
        <h2 class="section-title">Условия работы</h2>
        {% if vacancy.conditions %}
            <p><strong>Тип занятости:</strong> {{ vacancy.conditions.get_employment_display }}</p>
            <p><strong>Способ оформления:</strong> {{ vacancy.conditions.get_contract_display }}</p>
            <p><strong>Зарплата:</strong> {{ vacancy.conditions.salary }}</p>
            <p><strong>Удалённая работа:</strong> {{ vacancy.conditions.remote_work|yesno:"Да,Нет" }}</p>
            <p><strong>Частота выплат:</strong> {{ vacancy.conditions.get_frequency_payments_display }}</p>
            <p><strong>Что получают работники:</strong> {{ vacancy.conditions.what_employees_get|default:"Информация отсутствует" }}</p>
        {% else %}
            <p>Условия работы отсутствуют.</p>
        {% endif %}
    </div>
    <div class="show-container">
        <h2 class="section-title">Контакты</h2>
            <p><strong>Телефон:</strong> {{ vacancy.company.company_phone }} Звонить в рабочее время с 09:00 до 18:00 по будням.</p>
            <p><strong>Email компании:</strong> {{ vacancy.company.company_email }}</p>
            <p><strong>Адрес:</strong> {{ vacancy.company.company_address }}</p>
            {% if vacancy.company.company_site %}
            <p><strong>Сайт:</strong> {{ vacancy.company.company_site }}</p>
            {% endif %}
    </div>
</div>

{% endblock %}