help/urls.py
from django.urls import path
from . import views


app_name = 'help'

urlpatterns = [
    path('make-a-ticket/', views.MakeTicket.as_view(), name='makeTicket'),
]

services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create-service/', views.createService, name='createService'),
    path('service/<int:pk>/delete/', views.delete_service, name='delete_service'),
    path('service/<int:service_id>/feedback/', views.create_feedback, name='create_feedback'),
    path('services/', views.ListServices.as_view(), name='services'),
    path('service/<int:pk>/', views.ShowService.as_view(), name='showService'),
    path('sort-services/', views.SortServices.as_view(), name='sortServices'),
    path('filtering-services/', views.FilteringServices.as_view(), name='filteringServices'),
    path('search-services/', views.SearchServices.as_view(), name='searchServices'),
    path('update-service/<int:service_id>', views.updateService, name='updateService'),
    path('service/delete-photo/<int:photo_id>/', views.delete_service_photo, name='delete_service_photo'),
]

staffsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # URL для административного интерфейса
    path('', RedirectView.as_view(url='resumes', permanent=True), name='index'),  # Редирект на 'resumes'
    path('', include('resume.urls')),  # Включение URL-ов приложения 'resume'
    path('', include('services.urls')),  # Включение URL-ов приложения 'services'
    path('', include('vacancy.urls')),  # Включение URL-ов приложения 'vacancy'
    path('users/', include('users.urls', namespace='users')),  # Включение URL-ов приложения 'users' с пространством имен
    path('info/', include('info.urls', namespace='info')),  # Включение URL-ов приложения 'info' с пространством имен
    path('help/', include('help.urls', namespace='help')),  # Включение URL-ов приложения 'help' с пространством имен
    path('__debug__/', include("debug_toolbar.urls")),  # URL для панели отладки
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Настройка URL для медиафайлов

services/models.py
from django.contrib.auth.models import User
from django.db import models
from djmoney.models.fields import MoneyField


# Create your models here.
class Service(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='services')
    name = models.CharField(max_length=50, verbose_name='Название услуги')
    EXPERIENCE_CHOICES = (
        ('without-experience', 'Без опыта'),
        ('less-than-year', 'Менее года'),
        ('1', '1 год'),
        ('2', '2 года'),
        ('3', '3 года'),
        ('4', '4 года'),
        ('5', '5 лет'),
        ('6', '6 лет'),
        ('7', '7 лет'),
        ('8', '8 лет'),
        ('9', '9 лет'),
        ('10', '10 лет'),
        ('more-than-10', 'Более 10 лет'),
    )
    GROUP_CHOICES = (
        ('1', '1 человек'),
        ('2-4', '2-4 человека'),
        ('5-10', '5-10 человек'),
        ('11-20', '11-20 человек'),
        ('20+', 'от 20 человек'),
    )
    experience = models.CharField(max_length=18, choices=EXPERIENCE_CHOICES, verbose_name='Опыт работы')
    group = models.CharField(max_length=18, choices=GROUP_CHOICES, default='1', verbose_name='Состав группы')
    description = models.TextField(verbose_name='Описание услуги', blank=False)
    price_list = models.TextField(verbose_name='Прайс-лист', blank=True, null=True)
    cost = MoneyField(max_digits=10, decimal_places=2, default_currency='RUB', verbose_name='Стоимость основной услуги')
    phone = models.CharField(max_length=12, verbose_name='Телефон', blank=False)
    email = models.EmailField(max_length=100, verbose_name='Электронная почта', blank=True, null=True)
    date_uploaded = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания резюме')
    date_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления резюме')

    def __str__(self):
        return f"Услуга {self.name} {self.cost}"

    class Meta:
        verbose_name = "Услугу"
        verbose_name_plural = "Услуги"


class Photos(models.Model):
    service = models.ForeignKey('Service', on_delete=models.CASCADE, related_name='photos')
    image = models.ImageField(upload_to='photo/resume_images/%Y/%m/%d', verbose_name='Фотографии', blank=True,
                              null=True)

    class Meta:
        verbose_name = "Фотографию"
        verbose_name_plural = "Фотографии"


class Feedback(models.Model):
    ESTIMATION_CHOICES = (
        (1, '1 звезда'),
        (2, '2 звезды'),
        (3, '3 звезды'),
        (4, '4 звезды'),
        (5, '5 звезд'),
    )
    service = models.ForeignKey('Service', on_delete=models.CASCADE, related_name='feedback')
    estimation = models.IntegerField( choices=ESTIMATION_CHOICES, default=5, verbose_name='Оценка')
    feedback_text = models.TextField(verbose_name='Отзыв', blank=False)

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Additionally(models.Model):
    CONTRACT_CHOICES = (
        ('yes', 'Да'),
        ('no', 'Нет'),
    )
    WARRANTY_CHOICES = (
        ('yes', 'Есть'),
        ('no', 'Нет'),
    )
    PURCHASE_CHOICES = (
        ('yes', 'Возможна'),
        ('no', 'Нет'),
    )
    service = models.OneToOneField('Service', on_delete=models.CASCADE, related_name='additionally')
    contract = models.CharField(max_length=3, choices=CONTRACT_CHOICES, default='no', verbose_name='Контракт',
                                blank=True)
    warranty = models.CharField(max_length=3, choices=WARRANTY_CHOICES, default='no', verbose_name='Гарантия',
                                blank=True)
    minimum_order = MoneyField(max_digits=10, decimal_places=2, default_currency='RUB',
                               verbose_name='Минимальная сумма заказа', blank=True, null=True)
    purchase = models.CharField(max_length=3, choices=PURCHASE_CHOICES, default='no',
                                verbose_name='Закупка материалов', blank=True)
    car = models.CharField(max_length=3, choices=WARRANTY_CHOICES, default='no', verbose_name='Автомобиль',
                           blank=True)
    tools = models.CharField(max_length=3, choices=CONTRACT_CHOICES, default='no', verbose_name='Инструменты',
                             blank=True)

    class Meta:
        verbose_name = "Дополнения"
        verbose_name_plural = "Дополнения"

services/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Avg, Count
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

from .utils import DataMixin, ToolsMixin
from .models import Photos, Service
from .forms import ServiceForm, AdditionallyForm, FeedbackForm


# Create your views here.

@login_required(login_url='users:login')
def createService(request, *args, **kwargs):
    if request.method == 'POST':
        form_sf = ServiceForm(request.POST, prefix='service')
        form_af = AdditionallyForm(request.POST, prefix='additionally')

        if form_sf.is_valid() and form_af.is_valid():

            service_info = form_sf.save(commit=False)
            service_info.user = request.user
            service_info.save()

            additionally_info = form_af.save(commit=False)
            additionally_info.service = service_info
            additionally_info.save()

            images = request.FILES.getlist('images')
            for image in images:
                Photos.objects.create(
                    service=service_info,
                    image=image
                )
            return redirect('index')
    else:
        form_sf = ServiceForm(prefix='service')
        form_af = AdditionallyForm(prefix='additionally')
    data = {
        'title': 'Размещение услуги',
        'form_sf': form_sf,
        'form_af': form_af,
    }
    return render(request, 'services/createServices.html', context=data)


class ListServices(DataMixin, ListView):
    model = Service

    def get_queryset(self):
        # Добавляем аннотацию к queryset
        return Service.objects.annotate(feedback_count=Count('feedback'),average_rating=Avg('feedback__estimation'))


class ShowService(LoginRequiredMixin, DetailView):
    model = Service
    template_name = 'services/service.html'
    context_object_name = 'service'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Услуга - {self.object.name}"
        return context


@login_required(login_url='users:login')
def create_feedback(request, service_id):
    service = get_object_or_404(Service, id=service_id)

    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.service = service
            feedback.save()
            return redirect('showService', pk=service.id)
    else:
        form = FeedbackForm()

    return render(request, 'services/createFeedback.html', {'form': form, 'service': service})


@login_required(login_url='users:login')
def delete_service_photo(request, photo_id):
    photo = get_object_or_404(Photos, id=photo_id)
    if request.method == 'POST':
        photo.delete()
        messages.success(request, 'Фото успешно удалено.')
        return redirect('resumes')  # Перенаправление на список резюме
    data = {
        'title': 'Удаление фото',
        'obj': photo
    }
    return render(request, 'confirm_delete.html', data)


@login_required(login_url='users:login')
def delete_service(request, pk):
    service = get_object_or_404(Service, pk=pk, user=request.user)
    if request.method == 'POST':
        service.delete()
        messages.success(request, 'Услуга успешно удалена.')
        return redirect('services')
    data = {
        'title': 'Удаление услуги',
        'obj': service
    }
    return render(request, 'confirm_delete.html', data)


@login_required(login_url='users:login')
def updateService(request, service_id):
    service_info = get_object_or_404(Service, id=service_id, user=request.user)

    if request.method == 'POST':
        # Создаем формы с очищенными данными
        form_sf = ServiceForm(request.POST, instance=service_info, prefix='service')
        form_af = AdditionallyForm(request.POST, instance=service_info.additionally, prefix='additionally')

        # Проверяем валидность форм
        if all(form.is_valid() for form in [form_sf, form_af]):
            form_sf.save()
            form_af.save()
            images = request.FILES.getlist('images')
            for image in images:
                Photos.objects.create(
                    service=service_info,
                    image=image
                )
            return redirect('index')

    else:
        form_sf = ServiceForm(instance=service_info, prefix='service', initial={'cost': service_info.cost.amount})
        form_af = AdditionallyForm(instance=service_info.additionally, prefix='additionally', initial={'minimum_order': service_info.additionally.minimum_order.amount})

    photos = service_info.photos.all() if service_info.photos else []
    data = {
        'title': 'Редактирование услуги',
        'form_sf': form_sf,
        'form_af': form_af,
        'photos': photos,
    }
    return render(request, 'services/createServices.html', context=data)


class SortServices(DataMixin, ToolsMixin, ListView):

    def get_queryset(self):
        type_sort = self.request.GET.get('sort_field')
        if type_sort == 'sort_exp':
            return Service.objects.all().order_by('-experience')
        elif type_sort == 'sort_cost':
            return Service.objects.all().order_by('cost')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        type_sort = self.request.GET.get('sort_field', '')
        context['type_sort'] = type_sort
        return context


class FilteringServices(DataMixin, ToolsMixin, ListView):

    def get_queryset(self):
        queryset = Service.objects.all()
        cost_min = self.request.GET.get('cost_min', '')
        cost_max = self.request.GET.get('cost_max', '')
        estimation_min = self.request.GET.get('estimation_min', '')
        estimation_max = self.request.GET.get('estimation_max', '')
        work_experience = self.request.GET.get('work_experience', '')
        contract = self.request.GET.get('contract', '')
        warranty = self.request.GET.get('warranty', '')
        car = self.request.GET.get('car', '')
        tools = self.request.GET.get('tools', '')

        if cost_min != '':
            queryset = queryset.filter(cost__gte=cost_min)
        if cost_max != '':
            queryset = queryset.filter(cost__lte=cost_max)
        if estimation_min != '':
            queryset.annotate(average_rating=Avg('feedback__estimation'))
            queryset = queryset.filter(average_rating__gte=estimation_min)
        if estimation_max != '':
            queryset.annotate(average_rating=Avg('feedback__estimation'))
            queryset = queryset.filter(average_rating__lte=estimation_max)
        if work_experience != '':
            queryset = queryset.filter(experience=work_experience)
        if contract != '':
            queryset = queryset.filter(additionally__contract=contract)
        if warranty != '':
            queryset = queryset.filter(additionally__warranty=warranty)
        if car != '':
            queryset = queryset.filter(additionally__car=car)
        if tools != '':
            queryset = queryset.filter(additionally__tools=tools)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['cost_min'] = self.request.GET.get('cost_min', '')
        context['cost_max'] = self.request.GET.get('cost_max', '')
        context['estimation_min'] = self.request.GET.get('estimation_min', '')
        context['estimation_max'] = self.request.GET.get('estimation_max', '')
        context['work_experience'] = self.request.GET.get('work_experience', '')
        context['contract'] = self.request.GET.get('contract', '')
        context['warranty'] = self.request.GET.get('warranty', '')
        context['car'] = self.request.GET.get('car', '')
        context['tools'] = self.request.GET.get('tools', '')
        return context


class SearchServices(DataMixin, ToolsMixin, ListView):

    def get_queryset(self):
        return Service.objects.filter(Q(name__icontains=self.request.GET.get('q')) |
                                      Q(price_list__icontains=self.request.GET.get('q'))
                                      | Q(description__icontains=self.request.GET.get('q')))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = self.request.GET.get('q', '')
        context['search_query'] = search_query
        return context

services/templates/services/createFeedback.html
{% extends 'logo_menu.html'%}
{% load static %}
{% block head %}
<link type="text/css" rel="stylesheet" href="{% static 'services/css/style.css' %}"/>
{% endblock %}
{% block content %}
<!-- Блок Новая услуга -->
<form class="center-container" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="padding: 55px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Оставить отзыв на услугу: {{ service.name }} {{ service.cost }}</h2>
                    {{form.non_field_errors }}
                    <div>
                        <label>Оценка:</label>
                        {% for choice in form.estimation.field.choices %}
                        <input type="radio" id="star_{{ choice.0 }}" name="estimation" value="{{ choice.0 }}" hidden>
                        <label class="star" for="star_{{ choice.0 }}">★</label>
                        {% endfor %}
                    </div>
                    <label class="form-label">{{ form.feedback_text.label }}</label>
                    <div class="mb-3">
                        {{ form.feedback_text }}
                        {{ form.feedback_text.errors }}
                    </div>
                    <button class="btn btn-success" type="submit">Отправить отзыв</button>
                    <button type="reset" class="btn btn-danger" onclick="goBack()">Назад к услуге</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="{% static 'services/js/feedback_stars.js' %}"></script>
<script src="{% static 'js/go_back.js' %}"></script>
{% endblock %}

services/templates/services/createServices.html
{% extends 'logo_menu.html'%}
{% load static %}
{% block content %}
<!-- Блок Новая услуга -->
<form class="center-container" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="padding: 55px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Основная информация</h2>
                    {{form_sf.non_field_errors }}
                    {% for field in form_sf %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Конец блока Новая услуга -->

    <!-- Блок Дополнительно -->
    <div style="padding: 20px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Дополнительно</h2>
                    {{form_af.non_field_errors}}
                    {% for field in form_af %}
                    <label class="form-label">{{ field.label }}</label>
                    <div class="mb-3">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Конец блока Дополнительно -->
    <!-- Блок Фотографии работ -->
    <div style="padding: 20px"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="filters">
                    <h2 class="mb-3 fs-3">Фотографии работ</h2>
                    <!-- Фотографии работ -->
                    <div class="col-mb-12">
                        <label class="form-label">Ваши работы:</label>
                        <div class="image-preview">
                            {% for photo in photos %}
                            <div class="existing-photo-item mb-2" style="display: inline-block; margin-right: 10px;">
                                <img src="{{ photo.image.url }}" alt="Фото"
                                     class="preview-image" >
                                <p>
                                    <a href="{% url 'delete_service_photo' photo.pk %}"
                                       class="btn btn-danger btn-sm">Удалить</a>
                                </p>
                            </div>
                            {% empty %}
                             <label class="form-label">Фото работ отсутствует</label>
                            {% endfor %}
                        </div>
                        <input type="file" name="images" id="image-input" class="form-control" multiple>
                    </div>
                    <div id="image-preview"></div>
                    {% include 'includes/btns_submit_reset.html'%}
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Конец блока Фотографии работ -->
<script src="{% static 'js/images.js' %}"></script>

{% endblock %}

services/templates/services/listServices.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link type="text/css" rel="stylesheet" href="{% static 'services/css/style.css' %}"/>
{% endblock %}
{% block filters %}
<!-- Блок Фильтры -->
        <div class="col-3">
            <div class="filters">
                <h2 class="mb-3 fs-3">Фильтры</h2>
                <form action="{% url 'filteringServices' %}" name="customer-form">

                    <!-- Стоимость -->
                    <div class="mb-3">
                        <label class="form-label">Стоимость услуги</label>
                        <div class="input-group mb-3">
                            <span class="input-group-text">от</span>
                            <input type="number" name="cost_min" value="{{cost_min}}" class="form-control"
                                   placeholder="0">
                            <span class="input-group-text">₽</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text">до</span>
                            <input type="number" name="cost_max" value="{{cost_max}}" class="form-control"
                                   placeholder="100000">
                            <span class="input-group-text">₽</span>
                        </div>
                    </div>

                    <!-- Рейтинг исполнителя -->
                    <div class="mb-3">
                        <label class="form-label">Рейтинг исполнителя</label>
                        <div class="mb-3">
                            <div class="input-group mb-3">
                                <span class="input-group-text">от</span>
                                <input type="text" name="estimation_min" value="{{estimation_min}}" class="form-control"
                                       placeholder="1">
                                <span class="input-group-text">до</span>
                                <input type="text" name="estimation_max" value="{{estimation_max}}" class="form-control"
                                       placeholder="5">
                                <span class="input-group-text">звёзд</span>
                            </div>
                        </div>
                    </div>

                    <!-- Опыт работы -->
                    <div class="mb-3">
                        <label class="form-label">Опыт работы</label>
                        <select
                                name="work_experience"
                                id="work_experience"
                                class="form-select"
                        >
                            <option value=""></option>
                            {% for exp in Experience %}
                            <option value="{{exp.0}}" {% if work_experience == exp.0 %}selected{% endif %}>{{exp.1}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="yes" id="flexCheckContract" name="contract" {% if contract %} checked {% endif %}>
                        <label class="form-check-label" for="flexCheckContract">
                            Работа по контракту
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="yes" id="flexCheckWarranty" name="warranty" {% if warranty %} checked {% endif %}>
                        <label class="form-check-label" for="flexCheckWarranty">
                            Гарантия на работу
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="yes" id="flexCheckCar" name="car" {% if car %} checked {% endif %}>
                        <label class="form-check-label" for="flexCheckCar">
                            Свой автомобиль
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="yes" id="flexCheckTools" name="tools" {% if tools %} checked {% endif %}>
                        <label class="form-check-label" for="flexCheckTools">
                            Свои инструменты
                        </label>
                    </div>

                    <div class="r10"></div>
                    <button type="submit" class="btn btn-custom">Применить</button>
                    <a href="{% url 'services' %}" type="btn" class="btn btn-danger">Сбросить</a>
                </form>
            </div>
        </div>
        <!-- Конец блока фильтры -->
        {% endblock %}

        {% block Sort %}
        <!-- Сортировка -->
        <div class="col-8">
            <form action="{% url 'sortServices' %}" method="get">
                <div class="input-group">

                    <select
                            class="form-select"
                            id="inputGroupSelect04"
                            aria-label="Выберите сортировку..."
                            name="sort_field"
                    >
                        <option value="" {% if type_sort == '' %}selected{% endif %}>Сортировать по...</option>
                        <option value="sort_exp" {% if type_sort == 'sort_exp' %}selected{% endif %}>По опыту работы</option>
                        <option value="sort_cost" {% if type_sort == 'sort_cost' %}selected{% endif %}>По цене услуги</option>
                    </select>
                    <button class="btn btn-outline-secondary" type="submit">
                        Сортировать
                    </button>
                </div>
            </form>
            {% endblock%}
            {% block content %}
            {% for service in services %}
            <div class="r15"></div>
            <div class="girl">
                <div class="container">
                    <div class="row">
                        <div class="col-4">
                            <div class="image-content__main">
                                <div class="card-image__main">
                                    {% if service.photo %}
                                    <img src="{{ service.photo.url }}" alt="" class="card-img__main">
                                    {% else %}
                                    <img src="{{ default_image }}" alt="" class="card-img__main">
                                    {% endif %}
                                 </div>
                            </div>
                        </div>
                <div class="col-7">
                <span class="text_upd">Обновлено {{service.date_update }} </span><br>
                <a href="{% url 'showService' service.pk %}" class="text_name"><b>{{ service.name }}</b></a><br>
                <span class="some_text"><b>От {{ service.cost }} за услугу</b></span>
                <div class="some_text">
                    <b>{{ service.description|truncatechars:350 }}</b><br>
                    <p>Опыт работы {{ service.get_experience_display }}. Состав группы {{ service.get_group_display }}.<br>
                    {% if service.price_list %}
                    Прайс-лист: {{ service.price_list }}
                    {% endif %}
                    </p>
                </div>
                <div class="feedback-info">
                    <span class="feedback-count">{{ service.feedback_count }} отзыва(ов)</span><br>
                    <div class="rating">
                        {% with avg_rating=service.average_rating %}
                            {% for i in "11111" %}
                                {% if forloop.counter <= avg_rating %}
                                    <span class="selected">★</span>
                                {% else %}
                                    <span class="star">★</span>
                                {% endif %}
                            {% endfor %}
                        <span class="average-rating"> (Оценка: {{ avg_rating|floatformat:1 }})</span>
                        {% endwith %}
                    </div>
                </div>
                <a href="{% url 'showService' service.pk %}" type="button" class="btn btn-custom" >Подробнее</a>
            </div>
            </div>
            </div>
            </div>
            {% empty %}
            <div class="r5"></div>
            <p class="text_name"> Услуг по заданным критериям не найдено</p>
            {% endfor %}
            </div>
            {% endblock %}

services/templates/services/service.html
{% extends 'logo_menu.html'%}
{% load static %}
{% block content %}
<div style="padding: 40px"></div>
<div class="container">
    <div class="show-container">
        <h1>{{ service.name }}</h1>
        <p><strong>Описание услуги:</strong> {{ service.description }}</p>
        <p><strong>Опыт работы:</strong> {{ service.get_experience_display }}</p>
        <p><strong>Состав группы:</strong> {{ service.get_group_display }}</p>
        <p><strong>Стоимость:</strong> {{ service.cost }}</p>
        <p><strong>Прайс-лист:</strong> {{ service.price_list|default:"Отсутствует" }}</p>
        <p><strong>Телефон:</strong> {{ service.phone }}</p>
        <p><strong>Электронная почта:</strong> {{ service.email|default:"Не указана" }}</p>
        <p><strong>Дата создания:</strong> {{ service.date_uploaded }}</p>
        <p><strong>Дата обновления:</strong> {{ service.date_update }}</p>
    </div>

    <div class="show-container">
        <h2 class="section-title">Фотографии услуги</h2>
        {% for photo in service.photos.all %}
        <a href="{{ photo.image.url }}"><img src="{{ photo.image.url }}" alt="Фото услуги" class="service-photo"></a>
        {% empty %}
            <p>Нет доступных фотографий.</p>
        {% endfor %}
    </div>

    <div class="show-container">
        <h2 class="section-title">Отзывы</h2>
        {% for feedback in service.feedback.all %}
            <div>
                <p><strong>Оценка:</strong> {{ feedback.get_estimation_display }}</p>
                <p><strong>Отзыв:</strong> {{ feedback.feedback_text }}</p>
                <hr>
            </div>
        {% empty %}
            <p>Нет отзывов.</p>
        {% endfor %}
        <a href="{% url 'create_feedback' service.pk %}" type="button" class="btn btn-custom" >Оставить отзыв</a>
    </div>

    <div class="show-container">
        <h2 class="section-title">Дополнительные условия</h2>
        {% if service.additionally %}
            <p><strong>Контракт:</strong> {{ service.additionally.get_contract_display }}</p>
            <p><strong>Гарантия:</strong> {{ service.additionally.get_warranty_display }}</p>
            <p><strong>Минимальная сумма заказа:</strong> {{ service.additionally.minimum_order }}</p>
            <p><strong>Закупка материалов:</strong> {{ service.additionally.get_purchase_display }}</p>
            <p><strong>Автомобиль:</strong> {{ service.additionally.get_car_display }}</p>
            <p><strong>Инструменты:</strong> {{ service.additionally.get_tools_display }}</p>
        {% else %}
            <p>Дополнительные условия отсутствуют.</p>
        {% endif %}
    </div>
</div>

{% endblock %}